# build number
name: $(VERSION).$(rev:r)

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

variables:
  - name: VERSION
    value: '0.1'
  - name: PACKAGE_DIR
    value: $(System.DefaultWorkingDirectory)/services/tabler-world-notifications

  - group: AWS Germany
  - group: ENV Germany Shared

pr:
  branches:
    exclude:
      - '*'

trigger:
  branches:
    include:
      - develop

  paths:
    include:
      - packages/**/src/*
      - services/tabler-world-notifications/src/*
      - services/tabler-world-notifications/azure-pipelines.yml

stages:
  - template: ../devops/default-stages.yml
