# Expo Build
pool:
  vmImage: "macOS-latest"

variables:
  - group: "Apple Distribution"
  - group: "Expo"
  - group: "Play Store"
  - group: "git-crypt"

  - name: EXPO_SDK_VERSION
    value: "36.0.0"
  - name: TURTLE_VERSION
    value: "0.13.10"
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn

steps:
  # prepare node environment
  - template: ./node.yml

  # yarn /
  - template: ./yarn.yml
    parameters:
      SOURCEDIR: $(System.DefaultWorkingDirectory)
      YARN_CACHE_FOLDER: $(YARN_CACHE_FOLDER)

  # yarn /App
  - template: ./yarn.yml
    parameters:
      SOURCEDIR: $(System.DefaultWorkingDirectory)/apps/tabler-app
      YARN_CACHE_FOLDER: $(YARN_CACHE_FOLDER)

  # Init expo environment
  - template: ./init-expo.yml
    parameters:
      APPDIR: $(System.DefaultWorkingDirectory)/apps/tabler-app
      APP_VERSION: $(build.buildNumber)
      SOURCESDIR: $(System.DefaultWorkingDirectory)

  - task: DownloadSecureFile@1
    name: mobileprovision
    inputs:
      secureFile: "worldroundtableapp_AppStore.mobileprovision"

  - task: DownloadSecureFile@1
    name: iosCertificate
    inputs:
      secureFile: "App_TABLER_APP.p12"

  - task: DownloadSecureFile@1
    name: androidCertificate
    inputs:
      secureFile: "mobile-app.jks"

  # select xcode version
  - script: |
      sudo xcode-select -s /Applications/Xcode_11.3.1.app/Contents/Developer

  # run turtle build
  - script: |
      npm install -g expo-cli
      npm install -g turtle-cli@$(TURTLE_VERSION)

      turtle setup:ios --sdk-version $EXPO_SDK_VERSION

      export EXPO_IOS_DIST_P12_PASSWORD=$(APPLE_P12_PASSWORD)
      turtle build:ios -u $(EXPO_USERNAME) -p $(EXPO_PASSWORD) --team-id $(APPLE_TEAM_ID) --dist-p12-path $(iosCertificate.secureFilePath) --provisioning-profile-path $(mobileprovision.secureFilePath) --release-channel $(EXPO_RELEASE_CHANNEL)

      turtle setup:android --sdk-version $EXPO_SDK_VERSION

      export EXPO_ANDROID_KEYSTORE_PASSWORD=$(ANDROID_KEYSTORE_PASSWORD)
      export EXPO_ANDROID_KEY_PASSWORD=$(ANDROID_KEY_PASSWORD)
      turtle build:android -u $(EXPO_USERNAME) -p $(EXPO_PASSWORD) --keystore-path $(androidCertificate.secureFilePath) --keystore-alias $(ANDROID_KEYSTORE_ALIAS) -t app-bundle --release-channel deployment

      cd /users/vsts/expo-apps

      export A=$(ls *.aab)
      export i=$(ls *.ipa)

      echo "##vso[task.setvariable variable=iosArtifact]$i"
      echo "##vso[task.setvariable variable=androidArtifact]$A"

      echo "File name to publish Android"
      echo $A

      echo "File name to publish IOS"
      echo $i
    workingDirectory: $(System.DefaultWorkingDirectory)/apps/tabler-app
    env:
      APPLE_P12_PASSWORD: $(APPLE_P12_PASSWORD)
      EXPO_PASSWORD: $(EXPO_PASSWORD)
      ANDROID_KEYSTORE_PASSWORD: $(ANDROID_KEYSTORE_PASSWORD)
      ANDROID_KEY_PASSWORD: $(ANDROID_KEY_PASSWORD)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "/users/vsts/expo-apps/$(iosArtifact)"
      ArtifactName: "ios"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "/users/vsts/expo-apps/$(androidArtifact)"
      ArtifactName: "android"
