stages:
  - stage: compile
    jobs:
      - job: dev
        variables:
          - group: ENV Germany DEV
        steps:
          - template: ./package-service.yml
            parameters:
              PACKAGE_DIR: $(PACKAGE_DIR)
              INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - job: test
        variables:
          - group: ENV Germany TEST
        steps:
          - template: ./package-service.yml
            parameters:
              PACKAGE_DIR: $(PACKAGE_DIR)
              INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

      - job: prod
        variables:
          - group: ENV Germany PROD
        steps:
          - template: ./package-service.yml
            parameters:
              PACKAGE_DIR: $(PACKAGE_DIR)
              INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - stage: dev
    dependsOn: compile
    jobs:
      - deployment: aws
        environment: tabler-world-dev
        variables:
          - group: ENV Germany DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./service.yml
                  parameters:
                    INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
                    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
                    PACKAGE_DIR: $(PACKAGE_DIR)

  - stage: test
    dependsOn: dev
    jobs:
      - deployment: aws
        environment: tabler-world-test
        variables:
          - group: ENV Germany TEST
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./service.yml
                  parameters:
                    INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
                    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
                    PACKAGE_DIR: $(PACKAGE_DIR)

  - stage: prod
    dependsOn: test
    jobs:
      - deployment: aws
        environment: tabler-world-prod
        variables:
          - group: ENV Germany PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./service.yml
                  parameters:
                    INFRASTRUCTURE_RELEASE_CHANNEL: $(INFRASTRUCTURE_RELEASE_CHANNEL)
                    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
                    PACKAGE_DIR: $(PACKAGE_DIR)
