parameters:
  PACKAGE_DIR: $(System.DefaultWorkingDirectory)
  INFRASTRUCTURE_RELEASE_CHANNEL: dev
  AWS_DEFAULT_REGION: eu-west-1

steps:
  - task: Npm@1
    inputs:
      command: custom
      workingDir: ${{ parameters.PACKAGE_DIR }}
      customCommand: "version $(Build.BuildNumber)"
    displayName: Bumping version

  - template: ./yarn.yml
    parameters:
      SOURCEDIR: $(System.DefaultWorkingDirectory)

  - script: |
      yarn build-common
      yarn build-cache
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Build command and cache

  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
    inputs:
      awsCredentials: AWS
      regionName: ${{ parameters.AWS_DEFAULT_REGION }}
      scriptType: inline
      inlineScript: |
        export NODE_OPTIONS=--max-old-space-size=8096
        yarn serverless package --stage ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }} --package ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}

      disableAutoCwd: true
      workingDirectory: ${{ parameters.PACKAGE_DIR }}
    displayName: Building package

  - publish: ${{ parameters.PACKAGE_DIR }}/${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}
    artifact: ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}
    displayName: Publishing package
