parameters:
  INFRASTRUCTURE_RELEASE_CHANNEL: dev
  AWS_DEFAULT_REGION: eu-west-1

steps:
  - download: current
    artifact: $(INFRASTRUCTURE_RELEASE_CHANNEL)

  - script: |
      yarn build-common
      yarn build-cache
    workingDirectory: $(System.DefaultWorkingDirectory)

  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
    inputs:
      awsCredentials: AWS
      regionName: ${{ parameters.AWS_DEFAULT_REGION }}
      scriptType: inline
      inlineScript: |
        npm install -g serverless
        npx serverless deploy --stage ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }} --package $(PIPELINE.WORKSPACE)/${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}

      disableAutoCwd: true
