parameters:
  INFRASTRUCTURE_RELEASE_CHANNEL: dev
  AWS_DEFAULT_REGION: eu-west-1
  PACKAGE_DIR: $(System.DefaultWorkingDirectory)

steps:
  - checkout: self

  - download: current
    artifact: ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}
    displayName: Downloading package

  - script: |
      sudo npm install -g serverless
    displayName: Installing serverless

  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
    inputs:
      awsCredentials: AWS
      regionName: ${{ parameters.AWS_DEFAULT_REGION }}
      scriptType: inline
      inlineScript: |
        sudo npx serverless deploy --stage ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }} --package $(PIPELINE.WORKSPACE)/${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}

      disableAutoCwd: true
      workingDirectory: ${{ parameters.PACKAGE_DIR }}

    displayName: Deploying package
