parameters:
  PACKAGE_DIR: $(System.DefaultWorkingDirectory)
  INFRASTRUCTURE_RELEASE_CHANNEL: dev
  AWS_DEFAULT_REGION: eu-west-1

steps:
  - task: Npm@1
    inputs:
      command: custom
      workingDir: ${{ parameters.PACKAGE_DIR }}
      customCommand: "version $(Build.BuildNumber)"

  - template: ../devops/yarn.yml
    parameters:
      SOURCEDIR: ${{ parameters.PACKAGE_DIR }}

  - script: |
      yarn build-common
      yarn build-cache
    workingDirectory: $(System.DefaultWorkingDirectory)

  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
    inputs:
      awsCredentials: AWS
      regionName: ${{ parameters.AWS_DEFAULT_REGION }}
      scriptType: inline
      inlineScript: |
        export NODE_OPTIONS=--max-old-space-size=8096
        yarn serverless deploy --stage ${{ parameters.PACKAGE_DIR }}

      disableAutoCwd: true
      workingDirectory: ${{ parameters.PACKAGE_DIR }}
