parameters:
  INFRASTRUCTURE_RELEASE_CHANNEL: dev
  AWS_DEFAULT_REGION: eu-west-1

steps:
  - download: current
    artifact: $(INFRASTRUCTURE_RELEASE_CHANNEL)
    displayName: Downloading package

  - script: |
      sudo npm install -g serverless
    displayName: Installing serverless

  - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
    inputs:
      awsCredentials: AWS
      regionName: ${{ parameters.AWS_DEFAULT_REGION }}
      scriptType: inline
      inlineScript: |
        npx serverless deploy --stage ${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }} --package $(PIPELINE.WORKSPACE)/${{ parameters.INFRASTRUCTURE_RELEASE_CHANNEL }}

      disableAutoCwd: true
    displayName: Deploying package
