parameters:
  SOURCEDIR: $(System.DefaultWorkingDirectory)
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
    displayName: "Use Yarn 1.22.4"
    inputs:
      versionSpec: 1.22.4
      checkLatest: true

  # - task: Cache@2
  #   displayName: Cache Yarn packages
  #   inputs:
  #     key: "services | $(Agent.OS) | ${{ parameters.SOURCEDIR }}/yarn.lock"
  #     path: ${{ parameters.YARN_CACHE_FOLDER }}

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
    displayName: install
    inputs:
      projectDirectory: ${{ parameters.SOURCEDIR }}
      arguments: install --frozen-lockfile
