# build number
name: $(VERSION).$(PATCH)

pool:
  name: 'Hosted Ubuntu 1604'
  # name: 'Default'
  demands: npm
  workspace:
    clean: all

variables:
  - name: VERSION
    value: '1.2'
  - name: PATCH
    value: $[counter(variables['VERSION'], 0)]
  - name: ANDROID_VERSION
    value: $[counter('ANDROID_VERSION', 11070)]
  - name: EXPO_RELEASE_CHANNEL
    value: '1.2-rc2' # was $(build.buildNumber)-$(EXPO_RELEASE_CHANNEL)
  - group: 'expo'
  - group: 'git-crypt'
  - group: 'AWS Germany'
  - group: 'ENV Germany Shared'
  - group: 'ENV Germany TEST'
  - name: YARN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.yarn

pr:
  branches:
    exclude:
      - '*'

trigger:
  branches:
    include:
      - release/v1.2

  paths:
    include:
      - apps/tabler-app/tsconfig.json
      - apps/tabler-app/yarn.lock
      - apps/tabler-app/azure-pipelines.yml
      - apps/tabler-app/src/*
      - apps/tabler-app/devops/*
      - apps/tabler-app/assets/docs/*
      - apps/tabler-app/assets/fonts/*
      - apps/tabler-app/assets/images/*
      - apps/tabler-app/config/app.json

steps:
# - powershell: |
#     Write-Host 'Patch# $(PATCH)'
#     $n = ([int]'$(PATCH)').tostring('000')
#     Write-Host "##vso[build.updatebuildnumber]$(VERSION).$($n)"

#   displayName: Define build#

- script: 'echo "$(git log -1 --pretty=%B)" > commit.txt'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: Save commit message

# prepare node environment
- template: ./devops/node.yml

# yarn /
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)
    YARN_CACHE_FOLDER: $(YARN_CACHE_FOLDER)

# yarn /App
- template: ./devops/yarn.yml
  parameters:
    SOURCEDIR: $(System.DefaultWorkingDirectory)/apps/tabler-app
    YARN_CACHE_FOLDER: $(YARN_CACHE_FOLDER)

# Init expo environment
- template: ./devops/init-expo.yml
  parameters:
    APPDIR: $(System.DefaultWorkingDirectory)/apps/tabler-app
    APP_VERSION: $(build.buildNumber)
    SOURCESDIR: $(System.DefaultWorkingDirectory)

- script: npm run licenses
  workingDirectory: '$(System.DefaultWorkingDirectory)/apps/tabler-app'
  displayName: licenses

# Publish expo
- script: |
    echo "Release is $EXPO_RELEASE_CHANNEL"
    npx expo publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL
    npx expo publish:history --release-channel $EXPO_RELEASE_CHANNEL -r > deployment.json
  workingDirectory: '$(System.DefaultWorkingDirectory)/apps/tabler-app'
  displayName: publish
  env:
    SENTRY_AUTH_TOKEN: $(SENTRY_AUTH_TOKEN)
    EXPO_RELEASE_CHANNEL: $(EXPO_RELEASE_CHANNEL)

# yarn /App
- template: ./devops/publish.yml
