const ___DONT_USE_ME_DIRECTLY___COLOR_RTI = '#ffbf35';
const ___DONT_USE_ME_DIRECTLY___COLOR_LCI = '#272A69';
const ___DONT_USE_ME_DIRECTLY___COLOR_AGORA = '#477A39';
const ___DONT_USE_ME_DIRECTLY___COLOR_C41 = '#F4B441';
const ___DONT_USE_ME_DIRECTLY___COLOR_TANGENT = '#BFBEBD';

export const ___DONT_USE_ME_DIRECTLY___COLOR_ACCENT = ___DONT_USE_ME_DIRECTLY___COLOR_RTI;
export const ___DONT_USE_ME_DIRECTLY___COLOR_BOTTOM_BAR = '#3a3a3a';
export const ___DONT_USE_ME_DIRECTLY___COLOR_GRAY = '#777';
export const ___DONT_USE_ME_DIRECTLY___COLOR_PIN = '#eb6752';
